In [1]:
import xarray as xr

ds = xr.open_dataset("Data/adaptor.mars.internal-1683063403.0277715-7525-8-8790778d-74f9-4ac2-80e1-9299cdaeb83b.grib", engine="cfgrib")
ds2 = xr.open_dataset("Data/adaptor.mars.internal-1683063474.2833943-13669-8-924f6f03-5ec6-4870-b3fd-166ab1c49b19.grib", engine="cfgrib")

Ignoring index file 'Data/adaptor.mars.internal-1683063403.0277715-7525-8-8790778d-74f9-4ac2-80e1-9299cdaeb83b.grib.923a8.idx' incompatible with GRIB file
Can't read index file 'Data/adaptor.mars.internal-1683063474.2833943-13669-8-924f6f03-5ec6-4870-b3fd-166ab1c49b19.grib.923a8.idx'
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/tfm/lib/python3.11/site-packages/cfgrib/messages.py", line 547, in from_indexpath_or_filestream
    self = cls.from_indexpath(indexpath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Caskroom/miniconda/base/envs/tfm/lib/python3.11/site-packages/cfgrib/messages.py", line 429, in from_indexpath
    index = pickle.load(file)
            ^^^^^^^^^^^^^^^^^
EOFError: Ran out of input

In [5]:
for v in ds:
    print("{}, {}, {}".format(v, ds[v].attrs["long_name"], ds[v].attrs["units"]))

u100, 100 metre U wind component, m s**-1
v100, 100 metre V wind component, m s**-1
u10n, Neutral wind at 10 m u-component, m s**-1
u10, 10 metre U wind component, m s**-1
v10n, Neutral wind at 10 m v-component, m s**-1
v10, 10 metre V wind component, m s**-1
d2m, 2 metre dewpoint temperature, K
t2m, 2 metre temperature, K
hcc, High cloud cover, (0 - 1)
lcc, Low cloud cover, (0 - 1)
msl, Mean sea level pressure, Pa
mcc, Medium cloud cover, (0 - 1)
sp, Surface pressure, Pa
tcc, Total cloud cover, (0 - 1)

In [2]:
ds = ds.get(['u100', 'v100'])
ds2 = ds2.get(['u100', 'v100'])

In [3]:
df = ds.to_dataframe()
df2 = ds2.to_dataframe()

In [13]:
df.iloc[:15]

                                   u100      v100  number   step  surface  \
time       latitude longitude
2020-12-01 43.00    -4.00      0.797363 -1.981216       0 0 days      0.0
                    -3.75      1.196777 -2.006607       0 0 days      0.0
                    -3.50      1.452637 -1.740982       0 0 days      0.0
                    -3.25      1.645020 -1.148209       0 0 days      0.0
                    -3.00      1.506348 -1.295670       0 0 days      0.0
           42.75    -4.00     -1.075684 -4.191177       0 0 days      0.0
                    -3.75     -0.427246 -3.996841       0 0 days      0.0
                    -3.50     -0.000488 -3.200943       0 0 days      0.0
                    -3.25      0.713379 -2.148209       0 0 days      0.0
                    -3.00      1.238770 -1.806412       0 0 days      0.0
           42.50    -4.00     -3.531738 -5.180435       0 0 days      0.0
                    -3.75     -2.882324 -4.678482       0 0 days      0.0
                    -3.50     -1.703613 -3.285904       0 0 days      0.0
                    -3.25     -0.186035 -1.859146       0 0 days      0.0
                    -3.00      0.908691 -1.504654       0 0 days      0.0

                              valid_time
time       latitude longitude
2020-12-01 43.00    -4.00     2020-12-01
                    -3.75     2020-12-01
                    -3.50     2020-12-01
                    -3.25     2020-12-01
                    -3.00     2020-12-01
           42.75    -4.00     2020-12-01
                    -3.75     2020-12-01
                    -3.50     2020-12-01
                    -3.25     2020-12-01
                    -3.00     2020-12-01
           42.50    -4.00     2020-12-01
                    -3.75     2020-12-01
                    -3.50     2020-12-01
                    -3.25     2020-12-01
                    -3.00     2020-12-01

In [5]:
df2

                                            u100      v100  number   step  \
time                latitude longitude
2021-01-01 00:00:00 43.0     -4.00      2.581390 -4.499176       0 0 days
                             -3.75      3.633148 -4.822418       0 0 days
                             -3.50      3.518890 -4.350739       0 0 days
                             -3.25      3.586273 -3.800934       0 0 days
                             -3.00      3.782562 -3.930817       0 0 days
...                                          ...       ...     ...    ...
2021-09-30 23:00:00 41.0     -4.00     -1.164551 -0.567505       0 0 days
                             -3.75     -0.664551 -0.965942       0 0 days
                             -3.50     -0.615723 -1.397583       0 0 days
                             -3.25     -0.412598 -1.958130       0 0 days
                             -3.00     -0.660645 -2.280396       0 0 days

                                        surface          valid_time
time                latitude longitude
2021-01-01 00:00:00 43.0     -4.00          0.0 2021-01-01 00:00:00
                             -3.75          0.0 2021-01-01 00:00:00
                             -3.50          0.0 2021-01-01 00:00:00
                             -3.25          0.0 2021-01-01 00:00:00
                             -3.00          0.0 2021-01-01 00:00:00
...                                         ...                 ...
2021-09-30 23:00:00 41.0     -4.00          0.0 2021-09-30 23:00:00
                             -3.75          0.0 2021-09-30 23:00:00
                             -3.50          0.0 2021-09-30 23:00:00
                             -3.25          0.0 2021-09-30 23:00:00
                             -3.00          0.0 2021-09-30 23:00:00

[294840 rows x 6 columns]