In [1]:
import xarray as xr

ds = xr.open_dataset("Data/adaptor.mars.internal-1683063403.0277715-7525-8-8790778d-74f9-4ac2-80e1-9299cdaeb83b.grib", engine="cfgrib")

Ignoring index file 'Data/adaptor.mars.internal-1683063403.0277715-7525-8-8790778d-74f9-4ac2-80e1-9299cdaeb83b.grib.923a8.idx' incompatible with GRIB file

In [5]:
for v in ds:
    print("{}, {}, {}".format(v, ds[v].attrs["long_name"], ds[v].attrs["units"]))

u100, 100 metre U wind component, m s**-1
v100, 100 metre V wind component, m s**-1
u10n, Neutral wind at 10 m u-component, m s**-1
u10, 10 metre U wind component, m s**-1
v10n, Neutral wind at 10 m v-component, m s**-1
v10, 10 metre V wind component, m s**-1
d2m, 2 metre dewpoint temperature, K
t2m, 2 metre temperature, K
hcc, High cloud cover, (0 - 1)
lcc, Low cloud cover, (0 - 1)
msl, Mean sea level pressure, Pa
mcc, Medium cloud cover, (0 - 1)
sp, Surface pressure, Pa
tcc, Total cloud cover, (0 - 1)

In [7]:
ds = ds.get(['u100', 'v100'])

In [8]:
df = ds.to_dataframe()

In [9]:
df

                                            u100      v100  number   step  \
time                latitude longitude
2020-12-01 00:00:00 43.0     -4.00      0.797363 -1.981216       0 0 days
                             -3.75      1.196777 -2.006607       0 0 days
                             -3.50      1.452637 -1.740982       0 0 days
                             -3.25      1.645020 -1.148209       0 0 days
                             -3.00      1.506348 -1.295670       0 0 days
...                                          ...       ...     ...    ...
2020-12-31 23:00:00 41.0     -4.00      4.517303 -1.604584       0 0 days
                             -3.75      3.785858 -2.112396       0 0 days
                             -3.50      3.002655 -1.683685       0 0 days
                             -3.25      2.988007 -1.947357       0 0 days
                             -3.00      3.347382 -1.598724       0 0 days

                                        surface          valid_time
time                latitude longitude
2020-12-01 00:00:00 43.0     -4.00          0.0 2020-12-01 00:00:00
                             -3.75          0.0 2020-12-01 00:00:00
                             -3.50          0.0 2020-12-01 00:00:00
                             -3.25          0.0 2020-12-01 00:00:00
                             -3.00          0.0 2020-12-01 00:00:00
...                                         ...                 ...
2020-12-31 23:00:00 41.0     -4.00          0.0 2020-12-31 23:00:00
                             -3.75          0.0 2020-12-31 23:00:00
                             -3.50          0.0 2020-12-31 23:00:00
                             -3.25          0.0 2020-12-31 23:00:00
                             -3.00          0.0 2020-12-31 23:00:00

[33480 rows x 6 columns]